{% set version = "12.8.1" %}

package:
  name: cuda-libraries-static
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 1
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart-static 12.8.90
    - cuda-nvrtc-static 12.8.93
    - libcublas-static 12.8.4.1      # [linux]
    - libcufft-static 11.3.3.83      # [linux]
    - libcufile-static 1.13.1.3       # [linux]
    - libcurand-static 10.3.9.90    # [linux]
    - libcusolver-static 11.7.3.90  # [linux]
    - libcusparse-static 12.5.8.93  # [linux]
    - libnpp-static 12.3.3.100         # [linux]
    - libnvfatbin-static 12.8.90
    - libnvjitlink-static 12.8.93
    - libnvjpeg-static 12.3.5.92     # [linux]

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library static packages.
  description: |
    Meta-package containing all available library static packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
