{% set version = "13.0.1" %}

package:
  name: cuda-libraries-static
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cudart-static 13.0.88
    - cuda-culibos-static 13.0.85    # [linux]
    - cuda-nvrtc-static 13.0.88
    - libcublas-static 13.0.2.14      # [linux]
    - libcufft-static 12.0.0.61      # [linux]
    - libcufile-static 1.15.1.6       # [linux]
    - libcurand-static 10.4.0.35    # [linux]
    - libcusolver-static 12.0.4.66  # [linux]
    - libcusparse-static 12.6.3.3  # [linux]
    - libnpp-static 13.0.1.2         # [linux]
    - libnvfatbin-static 13.0.85
    - libnvjitlink-static 13.0.88
    - libnvjpeg-static 13.0.1.86     # [linux]

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library static packages.
  description: |
    Meta-package containing all available library static packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
